### ISSUE TITLE
cypress-slack-reporter for GitLab ci cd pipelines

### ISSUE THREAD

**Issue by BartusZak** [YOU54F/cypress-plugins#1249] opened 2023-12-09 15:40 UTC
There is a lack of details about configuration with GitLab CI/CD.

Is it expected? Any hints if I can use it with GitLab CI/CD to send cypress e2e reports to a slack channel?

**Comment by YOU54F** [comment] 2024-01-15 17:33
See related issue https://github.com/YOU54F/cypress-plugins/issues/1160

In this [section](https://github.com/YOU54F/cypress-plugins/blob/master/cypress-slack-reporter-old/README.md#circleci) of the readme 


> If you wish to use another CI provider, you can pass any name other than `circleci` into the CLI flag `--ci-provider`, which will allow you to enter your own environment variables for CI.
> 
> - `CI_URL`
> - `CI_SHA1`,
> - `CI_BRANCH`,
> - `CI_USERNAME`,
> - `CI_BUILD_URL`,
> - `CI_BUILD_NUM`,
> - `CI_PULL_REQUEST`,
> - `CI_PROJECT_REPONAME`
> - `CI_PROJECT_USERNAME`

**Comment by YOU54F** [comment] 2024-01-15 17:34
duplicate of #1160

**Closed by YOU54F** 2024-01-15 17:34 UTC
